version: "3.9"

services:
    postgres:
        image: postgres:latest
        environment:
            POSTGRES_DB: "database"
            POSTGRES_USER: "admin"
            POSTGRES_PASSWORD: "testpass"
        ports:
            - "5432:5432"
        volumes:
            - ./volumes/postgres/data:var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d database"]
            interval: 10s
            timeout: 5s
            retries: 5
            start_period: 10s
        restart: unless-stopped

    pgadmin:
        image: dpage/pgadmin4:7.2
        environment:
            PGADMIN_DEFAULT_EMAIL: "admin@pgadmin.com"
            PGADMIN_DEFAULT_PASSWORD: "testpass"
        volumes:
            - ./volumes/pgadmin/data:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped
